[project]
name = "code-opt"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "jsonlines>=4.0.0",
    "openai>=2.15.0",
    "prettytable>=3.17.0",
    "pydantic>=2.12.5",
    "transformers==4.57.0",
]
